import { prisma } from '../lib/prisma.js';
import { DEMO_STORE_ID } from '../controllers/products.controller.js';

export const seedProductsIfEmpty = async () => {
  const count = await prisma.product.count();
  if (count > 0) return;

  await prisma.product.createMany({
    data: [
      {
        // id removed (uuid generated by DB)
        storeId: DEMO_STORE_ID,
        name: 'Power Drill Set',
        priceCents: 129000,
        currency: 'PHP',
        category: 'Tools',
        sku: 'TLS-PD-18V',
        description: 'Cordless power drill set for home and job site use.',
        imageUrl: 'https://picsum.photos/seed/p1/600/600',
        images: ['https://picsum.photos/seed/p1/600/600'],
        stock: 25,
        isActive: true,
      },
      {
        storeId: DEMO_STORE_ID,
        name: 'Circular Saw',
        priceCents: 149000,
        currency: 'PHP',
        category: 'Tools',
        sku: 'TLS-CS-185',
        description: 'Compact circular saw for wood and board cutting.',
        imageUrl: 'https://picsum.photos/seed/p2/600/600',
        images: ['https://picsum.photos/seed/p2/600/600'],
        stock: 18,
        isActive: true,
      },
      {
        storeId: DEMO_STORE_ID,
        name: 'Framing Hammer',
        priceCents: 89000,
        currency: 'PHP',
        category: 'Tools',
        sku: 'TLS-FH-20',
        description: 'Steel framing hammer with anti-slip grip.',
        imageUrl: 'https://picsum.photos/seed/p3/600/600',
        images: ['https://picsum.photos/seed/p3/600/600'],
        stock: 40,
        isActive: true,
      },
      {
        storeId: DEMO_STORE_ID,
        name: 'Measuring Tape',
        priceCents: 42000,
        currency: 'PHP',
        category: 'Tools',
        sku: 'TLS-MT-25',
        description: '25ft measuring tape with lock feature.',
        imageUrl: 'https://picsum.photos/seed/p4/600/600',
        images: ['https://picsum.photos/seed/p4/600/600'],
        stock: 56,
        isActive: true,
      },
      {
        storeId: DEMO_STORE_ID,
        name: 'Screwdriver Set',
        priceCents: 76000,
        currency: 'PHP',
        category: 'Tools',
        sku: 'TLS-SD-12',
        description: '12-piece screwdriver set for general repairs.',
        imageUrl: 'https://picsum.photos/seed/p5/600/600',
        images: ['https://picsum.photos/seed/p5/600/600'],
        stock: 32,
        isActive: true,
      },
      {
        storeId: DEMO_STORE_ID,
        name: 'Step Ladder',
        priceCents: 119000,
        currency: 'PHP',
        category: 'Tools',
        sku: 'TLS-SL-5FT',
        description: '5ft folding aluminum step ladder.',
        imageUrl: 'https://picsum.photos/seed/p6/600/600',
        images: ['https://picsum.photos/seed/p6/600/600'],
        stock: 14,
        isActive: true,
      },
    ],
    skipDuplicates: true,
  });
};